// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace VaccineManagementSystem.Models;

public partial class CommonVaccinetbl
{
    public int VaccineId { get; set; }

    [Required(ErrorMessage = "Vaccine Name is required")]
    public string VaccineName { get; set; }

    [Required(ErrorMessage = "Company Name is required")]
    public string CompanyName { get; set; }

    [Required(ErrorMessage = "Vaccine Description is required")]
    public string VaccineDesc { get; set; }

  
    public string VaccineImg { get; set; }

    [Required(ErrorMessage = "City is required")]
    public string City { get; set; }

    [Required(ErrorMessage = "State is required")]
    public string State { get; set; }

    [Required(ErrorMessage = "Quantity is required")]
    [Range(1, int.MaxValue, ErrorMessage = "Quantity must be a positive number")]
    public int Qty { get; set; }
}