// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace VaccineManagementSystem.Models;

public partial class FamilyMembersTbl
{
    public int MId { get; set; }

    public int? UserId { get; set; }

    [Required(ErrorMessage = "Name is required")]
    public string MName { get; set; }

    [Required(ErrorMessage = "Aadhar Number is required")]
    [RegularExpression(@"^\d{12}$", ErrorMessage = "Aadhar Number must be 12 digits")]
    public string MAadhaarNum { get; set; }

    [Required(ErrorMessage = "Date of Birth is required")]
    public DateOnly MDob { get; set; }

    [Required(ErrorMessage = "Relation is required")]
    public string Relation { get; set; }

    [Required(ErrorMessage = "Phone Number is required")]
    [RegularExpression(@"^\d{10}$", ErrorMessage = "Phone Number must be 10 digits")]
    public string PhoneNumber { get; set; }


    [Required(ErrorMessage = "Email is required")]
    [EmailAddress(ErrorMessage = "Invalid Email Address")]
    public string Email { get; set; }

    public virtual UserTbl User { get; set; }

    public virtual ICollection<VaccinationCertificate> VaccinationCertificates { get; set; } = new List<VaccinationCertificate>();

    public virtual ICollection<VaccineHistory> VaccineHistories { get; set; } = new List<VaccineHistory>();

    public virtual ICollection<VaccineSlotsTbl> VaccineSlotsTbls { get; set; } = new List<VaccineSlotsTbl>();
}