// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace VaccineManagementSystem.Models;

public partial class VaccineSlotsTbl
{
    public int SId { get; set; }

    [Required(ErrorMessage = "Slot booking time is required")]
    [DataType(DataType.Time)]
    public TimeOnly? SlotTime { get; set; }

    [Required(ErrorMessage = "Slot booking year is required")]
    [DataType(DataType.Date)]
    public DateOnly? YearDate { get; set; }

    public bool? IsBooked { get; set; }

    public int? BookedByUserId { get; set; }

    public int? BookedForFamilyMemberId { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public virtual UserTbl BookedByUser { get; set; }

    public virtual FamilyMembersTbl BookedForFamilyMember { get; set; }

    public virtual ICollection<VaccinationCertificate> VaccinationCertificates { get; set; } = new List<VaccinationCertificate>();

    public virtual ICollection<VaccineHistory> VaccineHistories { get; set; } = new List<VaccineHistory>();
}