// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VaccineManagementSystem.Models;

public partial class VaccineHistory
{
    public int Id { get; set; }

    public int? UserId { get; set; }

    public int? FamilyMemberId { get; set; }

    public int? VaccineSlotId { get; set; }

    public DateTime? VaccineDate { get; set; }

    public virtual FamilyMembersTbl FamilyMember { get; set; }

    public virtual UserTbl User { get; set; }

    public virtual VaccineSlotsTbl VaccineSlot { get; set; }
}